AWSTemplateFormatVersion: 2010-09-09
Description: >-
  routing-service
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  OrsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/ors.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 20
      Events:
        Api:
          Type: Api
          Properties:
            Path: /ors
            Method: POST
            Auth:
              Authorizer: AWS_IAM
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          ORS_API_KEY: 'placeholder'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
