AWSTemplateFormatVersion: 2010-09-09
Description: >-
  routing-service
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  OrsKey:
    Type: String
    Description: The API key for ors

Resources:
  CreateDeliveryJobsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/createDeliveryJobs.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 20
      Events:
        Api:
          Type: Api
          Properties:
            Path: /createDeliveryJobs
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          ORS_API_KEY: !Ref OrsKey
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true

  SnapFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/snap.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 20
      Events:
        Api:
          Type: Api
          Properties:
            Path: /snap
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          ORS_API_KEY: !Ref OrsKey
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
