AWSTemplateFormatVersion: '2010-09-09'
Description: Monolith

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  ExpressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  ExpressInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: S3ReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: arn:aws:s3:::metropack-builds/app.zip
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:Query
                Resource: !GetAtt MonolithVendorTable.Arn

  ExpressInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ExpressInstanceRole

  ExpressInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref ExpressSecurityGroup
      IamInstanceProfile: !Ref ExpressInstanceProfile
      ImageId: ami-02b7d5b1e55a7b5f1
      UserData:
        Fn::Base64: | 
          #!/bin/bash
          curl -sL https://rpm.nodesource.com/setup_18.x | bash -
          yum install -y nodejs unzip awscli
          aws s3 cp s3://metropack-builds/app.zip /home/ec2-user/app.zip
          unzip /home/ec2-user/app.zip -d /home/ec2-user/app
          cd /home/ec2-user/app
          npm install
          npm run build
          export VENDOR_TABLE=MonolithVendorTable
          export AWS_REGION=eu-central-1
          nohup node dist/index.js > app.log 2>&1 &


  MonolithVendorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MonolithVendorTable
      AttributeDefinitions:
        - AttributeName: vendorId
          AttributeType: S
        - AttributeName: eventOrder
          AttributeType: N
      KeySchema:
        - AttributeName: vendorId
          KeyType: HASH
        - AttributeName: eventOrder
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  InstancePublicIp:
    Description: Public IP of the EC2 instance
    Value: !GetAtt ExpressInstance.PublicIp