openapi: 3.0.1
info:
  title: DynamicPricingService API
  description: API for dynamic pricing service
  version: 1.0.0

paths:
  /putEvent:
    post:
      summary: Put an event to DynamicPricingServiceBus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Entries:
                  type: array
                  items:
                    type: object
                    properties:
                      version:
                        type: string
                      id:
                        type: string
                      detail-type:
                        type: string
                      source:
                        type: string
                      time:
                        type: string
                      region:
                        type: string
                      resources:
                        type: array
                        items:
                          type: string
                      detail:
                        type: object
                        properties:
                          metadata:
                            type: object
                            properties:
                              domain:
                                type: string
                              subdomain:
                                type: string
                              service:
                                type: string
                              category:
                                type: string
                              type:
                                type: string
                              name:
                                type: string
                          data:
                            type: object
      responses:
        '200':
          description: Event sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /createOffer:
    post:
      summary: Create offer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                version:
                  type: string
                buyer:
                  type: object
                  properties:
                    id:
                      type: string
                    city:
                      type: string
                    location:
                      type: object
                      properties:
                        latitude:
                          type: number
                        longitude:
                          type: number
                vendor:
                  type: object
                  properties:
                    id:
                      type: string
                    city:
                      type: string
                    location:
                      type: object
                      properties:
                        latitude:
                          type: number
                        longitude:
                          type: number
      responses:
        '200':
          description: Offer details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  offerId:
                    type: string
                  dates:
                    type: array
                    items:
                      type: object
                    properties:
                      date:
                        type: string
                      price:
                        type: number
                      currency:
                        type: string
                      availableCapacity:
                        type: number
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string