AWSTemplateFormatVersion: 2010-09-09
Description: DynamicPricingService API with Lambda integration

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  # API Gateway (REST API)
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: DynamicPricingServiceApi
      StageName: prod

  # Lambda function that sends events to EventBridge
  EventBridgeLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/eventBridgeHandler.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: events:PutEvents
              Resource: !GetAtt EventBus.Arn
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref EventBus
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /putEvent
            Method: POST
            RestApiId: !Ref ApiGateway
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true

  # EventBridge Bus
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: DynamicPricingServiceBus

  # Lambda function triggered when an offer is accepted
  OfferAcceptedFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: 'src/handlers/offerAccepted.handler'
      Runtime: 'nodejs22.x'
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        OfferAcceptedRule:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBus
            Pattern:
              detail-type:
                - 'dynamicPricingService.offerAccepted'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/putEvent"
